apiVersion: v1
kind: Pod
metadata:
  name: hello-app-1
  labels:
    group: greeting
spec:
  containers:
  - name: hello-app
    image: yoonjeong/hello-app:1.0
    port:
    - containerPort: 8080
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spce.nodeName
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    resources:
      limits:
        cpu: "50m"
        memory: "64Mi"